// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SponsorMyAthlete.Infrastructure.Persistence;

#nullable disable

namespace SponsorMyAthlete.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AdminFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AdminFlags");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthleteAccomplishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.ToTable("AthleteAccomplishments");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthletePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProfilePhoto")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.ToTable("AthletePhotos");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageReach")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("CompetitiveLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FacebookHandle")
                        .HasColumnType("text");

                    b.Property<int?>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("text");

                    b.Property<string>("Organisation")
                        .HasColumnType("text");

                    b.Property<string>("Sport")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationAdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("VerificationReference")
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeightClass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("Sport", "State");

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.BlockedMessageAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttemptedBody")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MatchedReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BlockedMessageAttempts");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeclaredValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("MessageThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("SponsorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StripePaymentLinkId")
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentLinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SponsorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.ProfileSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SponsorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId", "SponsorUserId")
                        .IsUnique();

                    b.ToTable("ProfileSaves");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.ProfileView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ViewerSponsorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId", "ViewedAt");

                    b.ToTable("ProfileViews");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abn")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("AbnEntityName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AbnValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AboutBlurb")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int?>("AthleteCountMax")
                        .HasColumnType("integer");

                    b.Property<int>("AthleteCountMin")
                        .HasColumnType("integer");

                    b.Property<string>("AthleteLevelPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AttendEvents")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("BudgetMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("BudgetMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("KeyDeliverablesWanted")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ReachImportance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RelationshipStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SponsorshipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<List<string>>("SportsOfInterest")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SponsorProfiles");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorWishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SponsorProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SponsorProfileId");

                    b.ToTable("SponsorWishlists");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorshipPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.ToTable("SponsorshipPackages");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("BlockedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("StripeDefaultPaymentMethodId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthleteAccomplishment", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.AthleteProfile", null)
                        .WithMany("Accomplishments")
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthletePhoto", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.AthleteProfile", null)
                        .WithMany("Photos")
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthleteProfile", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.User", "User")
                        .WithOne("AthleteProfile")
                        .HasForeignKey("SponsorMyAthlete.Domain.Entities.AthleteProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.Message", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.MessageThread", null)
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.MessageThread", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.Deal", "Deal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorProfile", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.User", "User")
                        .WithOne("SponsorProfile")
                        .HasForeignKey("SponsorMyAthlete.Domain.Entities.SponsorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorWishlist", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.SponsorProfile", null)
                        .WithMany("Wishlists")
                        .HasForeignKey("SponsorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorshipPackage", b =>
                {
                    b.HasOne("SponsorMyAthlete.Domain.Entities.AthleteProfile", null)
                        .WithMany("SponsorshipPackages")
                        .HasForeignKey("AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.AthleteProfile", b =>
                {
                    b.Navigation("Accomplishments");

                    b.Navigation("Photos");

                    b.Navigation("SponsorshipPackages");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.SponsorProfile", b =>
                {
                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("SponsorMyAthlete.Domain.Entities.User", b =>
                {
                    b.Navigation("AthleteProfile");

                    b.Navigation("SponsorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
